export const Categories = {
  TM: "M",
  TJ: "J",
  TS: "S",
  TK: "K",
  TW: "W",
  TN: "N",
};

const ROUND_1 = {
  number: 1,
  date: new Date("2024-02-18"),
  name: "XIX Mroźne Marsze na Orientację",
  shortName: "Mroźne MnO",
  location: "Nakło Śląskie",
  club: "KTK „be loć” Piekary Śląskie",
  shortClub: "be-loć",
  categories: [
    Categories.TM,
    Categories.TJ,
    Categories.TS,
    Categories.TK,
    Categories.TW,
    Categories.TN,
  ],
  eventFacebookLink: undefined,
  eventWebsiteLink: undefined,
  eventBulletinLink: "/rundy/2024_mrozne_regulamin.pdf",
};

const ROUND_2 = {
  number: 2,
  date: new Date("2024-02-24"),
  name: "LVI Zimowe Jazdy i Marsze na Orientację",
  shortName: "Zimowe JiMnO",
  location: "Kamionek",
  club: "GKT „Cyrkino” PTTK - Gliwice",
  shortClub: "Cyrkino",
  categories: [
    Categories.TM,
    Categories.TJ,
    Categories.TS,
    Categories.TK,
    Categories.TW,
    Categories.TN,
  ],
  eventFacebookLink: "https://www.facebook.com/events/284737334255518",
  eventWebsiteLink: undefined,
  eventBulletinLink: "/rundy/2024_zimowe_regulamin.pdf",
};

const ROUND_3 = {
  number: 3,
  date: new Date("2024-03-23"),
  name: "XLIV Marsze na Orientacje „Wiosna z kompasem”",
  shortName: "Wiosna z kompasem",
  location: "okolica Katowic",
  club: "„Czartak” PTTK - Katowice",
  shortClub: "Czartak",
  categories: [
    Categories.TM,
    Categories.TJ,
    Categories.TS,
    Categories.TK,
    Categories.TW,
    Categories.TN,
  ],
  eventFacebookLink: "https://www.facebook.com/events/2565326536984253",
  eventWebsiteLink: undefined,
  eventBulletinLink: "/rundy/2024_wiosna_regulamin.pdf",
};

const ROUND_4 = {
  number: 4,
  date: new Date("2024-04-06"),
  name: "III Primaaprilisowe MnO",
  shortName: "Primaaprilisowe MnO",
  location: "Chrzanów",
  club: "Stowarzyszenie Rozwoju Orienteeringu",
  additionalClub: "AKInO Kraków",
  shortClub: "Stowarzyszenie Rozwoju Orienteeringu / AKInO",
  categories: [
    Categories.TM,
    Categories.TJ,
    Categories.TS,
    Categories.TK,
    Categories.TW,
    Categories.TN,
  ],
  eventFacebookLink: "https://www.facebook.com/events/1604403080306004/",
  eventWebsiteLink: undefined,
  eventBulletinLink: "/rundy/2024_primaaprilisowe_regulamin.pdf",
};

const ROUND_5 = {
  number: 5,
  date: new Date("2024-08-04"),
  name: "II MnO Pełnia Lata",
  shortName: "MnO Pełnia Lata",
  location: "Dąbrowa Górnicza",
  club: "Stowarzyszenie Rozwoju Orienteeringu",
  additionalClub: "AKInO Kraków",
  shortClub: "Stowarzyszenie Rozwoju Orienteeringu / AKInO",
  categories: [
    Categories.TM,
    Categories.TJ,
    Categories.TS,
    Categories.TK,
    Categories.TW,
    Categories.TN,
  ],
  eventFacebookLink: undefined,
  eventWebsiteLink: undefined,
  eventBulletinLink: undefined,
};

const ROUND_6 = {
  number: 6,
  date: new Date("2024-09-14"),
  name: "Diablino 2024",
  shortName: "Diablino",
  location: "okolica Piekar Śląskich",
  club: "KTK „be loć” Piekary Śląskie",
  shortClub: "be-loć",
  categories: [
    Categories.TM,
    Categories.TJ,
    Categories.TS,
    Categories.TK,
    Categories.TW,
    Categories.TN,
  ],
  eventFacebookLink: undefined,
  eventWebsiteLink: undefined,
  eventBulletinLink: undefined,
};

const ROUND_7 = {
  number: 7,
  date: new Date("2024-10-05"),
  name: "XLIII Marsze na Orientację „Jesień z kompasem”",
  shortName: "Jesień z kompasem",
  location: "okolica Katowic",
  club: "„Czartak” PTTK - Katowice",
  shortClub: "Czartak",
  categories: [
    Categories.TM,
    Categories.TJ,
    Categories.TS,
    Categories.TK,
    Categories.TW,
    Categories.TN,
  ],
  eventFacebookLink: undefined,
  eventWebsiteLink: undefined,
  eventBulletinLink: undefined,
};

const ROUND_8 = {
  number: 8,
  date: new Date("2024-11-16"),
  name: "MnO 1000002024",
  shortName: "MnO 1000002024",
  location: "Beskid Śląski",
  club: "PKT Plessino - Pszczyna",
  additionalClub: "Sino TPL „Krokus Miliardowice” – Ligota",
  shortClub: "Plessino / Krokus",
  categories: [
    Categories.TM,
    Categories.TJ,
    Categories.TS,
    Categories.TK,
    Categories.TW,
    Categories.TN,
  ],
  eventFacebookLink: undefined,
  eventWebsiteLink: undefined,
  eventBulletinLink: undefined,
};

const ROUND_9 = {
  number: 9,
  date: new Date("2024-12-07"),
  name: "LV Barbórkowe Marsze na Orientację",
  additionalName: "LV Nocne Marsze na Orientację",
  shortName: "Barbórkowe i Nocne",
  location: "okolica Gliwic",
  club: "GKT „Cyrkino” PTTK - Gliwice",
  shortClub: "Cyrkino",
  categories: [
    Categories.TM,
    Categories.TJ,
    Categories.TS,
    Categories.TK,
    Categories.TW,
    Categories.TN,
  ],
  eventFacebookLink: undefined,
  eventWebsiteLink: undefined,
  eventBulletinLink: undefined,
};

export const ROUNDS = [
  ROUND_1,
  ROUND_2,
  ROUND_3,
  ROUND_4,
  ROUND_5,
  ROUND_6,
  ROUND_7,
  ROUND_8,
  ROUND_9,
];
